platform:ios, '6.0'
pod 'SWSnapshotStackView', '~> 0.0.1'
pod 'FTWButton', '~> 1.0'
pod 'CTAssetsPickerController', '~> 1.2.1'
pod 'MBProgressHUD', '~> 0.8'
pod 'SBJson', '~> 3.2'
pod 'CMPopTipView', '~> 2.0.0'
pod 'WCAlertView', '~> 1.0.1'
pod 'GPUImage', '~> 0.1.2'
