//
//  StaticFilterMapping.h
//  MirroFx
//
//  Created by Vijaya kumar reddy Doddavala on 10/16/12.
//  Copyright (c) 2012 Cell Phone. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "config.h"
#import "PhotoEffects_Config.h"

typedef enum
{
#if MIRRORSET_SUPPORT
    GROUP_STATIC_FILTER_MIRROR,
#endif
#if COLORGROUP_SUPPORT
    GROUP_STATIC_GPU_FILTER_COLOR,
#endif
#if VINTAGEGROUP_SUPPORT
    GROUP_STATIC_GPU_FILTER_VINTAGE,
#endif
#if TONEGROUP_SUPPORT
    GROUP_STATIC_GPU_FILTER_TONE,
#endif
#if SKETCHGROUP_SUPPORT
    GROUP_STATIC_GPU_FILTER_SKETCH,
#endif
#if CARTOONGROUP_SUPPORT
    GROUP_STATIC_GPU_FILTER_CARTOON,
#endif
#if GRUNGEGROUP_SUPPORT
    GROUP_STATIC_FILTER_GRUNGE,
#endif
#if TEXTUREGROUP_SUPPORT
    GROUP_STATIC_FILTER_TEXTURE,
#endif
#if SPACEGROUP_SUPPORT
    GROUP_STATIC_FILTER_SPACE,
#endif
#if BOKEHGROUP_SUPPORT
    GROUP_STATIC_FILTER_BOKEH,
#endif
#if FRAMEGROUP_SUPPORT
    GROUP_STATIC_FILTER_FRAME,
#endif
#if NOISESET_SUPPORT
    GROUP_STATIC_FILTER_NOISE,
#endif
    GROUP_STATIC_FILTER_LAST
}eGroupStaticFilter;

#if VINTAGEGROUP_SUPPORT
typedef enum
{
    STATIC_GPU_FILTER_VINTAGE_EFFECT1,
    STATIC_GPU_FILTER_VINTAGE_EFFECT2,
    STATIC_GPU_FILTER_VINTAGE_EFFECT3,
    STATIC_GPU_FILTER_VINTAGE_EFFECT4,
    STATIC_GPU_FILTER_VINTAGE_EFFECT5,
    STATIC_GPU_FILTER_VINTAGE_EFFECT6,
    STATIC_GPU_FILTER_VINTAGE_EFFECT7,
    STATIC_GPU_FILTER_VINTAGE_EFFECT_LAST,
}eStaticVintageFilter;
#endif
#if CARTOONGROUP_SUPPORT
typedef enum
{
    STATIC_GPU_FILTER_TOON_EFFECT1,
    STATIC_GPU_FILTER_TOON_EFFECT2,
    STATIC_GPU_FILTER_TOON_EFFECT3,
    STATIC_GPU_FILTER_TOON_EFFECT4,
    STATIC_GPU_FILTER_TOON_EFFECT5,
    STATIC_GPU_FILTER_TOON_EFFECT6,
    STATIC_GPU_FILTER_TOON_EFFECT7,
    STATIC_GPU_FILTER_TOON_EFFECT_LAST,
}eStaticToonFilter;
#endif

#if TONEGROUP_SUPPORT
typedef enum
{
    STATIC_GPU_FILTER_TONE_EFFECT1,
    STATIC_GPU_FILTER_TONE_EFFECT2,
    STATIC_GPU_FILTER_TONE_EFFECT3,
    STATIC_GPU_FILTER_TONE_EFFECT4,
    STATIC_GPU_FILTER_TONE_EFFECT5,
    STATIC_GPU_FILTER_TONE_EFFECT6,
    STATIC_GPU_FILTER_TONE_EFFECT7,
    STATIC_GPU_FILTER_TONE_EFFECT_LAST,
}eStaticToneFilter;
#endif

#if SKETCHGROUP_SUPPORT
typedef enum
{
    STATIC_GPU_FILTER_SKETCH_EFFECT1,
    STATIC_GPU_FILTER_SKETCH_EFFECT2,
    STATIC_GPU_FILTER_SKETCH_EFFECT3,
    STATIC_GPU_FILTER_SKETCH_EFFECT4,
    STATIC_GPU_FILTER_SKETCH_EFFECT5,
    STATIC_GPU_FILTER_SKETCH_EFFECT6,
    STATIC_GPU_FILTER_SKETCH_EFFECT7,
    STATIC_GPU_FILTER_SKETCH_EFFECT_LAST,
}eStaticSketchFilter;
#endif

#if COLORGROUP_SUPPORT
typedef enum
{
    STATIC_GPU_FILTER_COLOR_EFFECT1,
    STATIC_GPU_FILTER_COLOR_EFFECT2,
    STATIC_GPU_FILTER_COLOR_EFFECT3,
    STATIC_GPU_FILTER_COLOR_EFFECT4,
    STATIC_GPU_FILTER_COLOR_EFFECT5,
    STATIC_GPU_FILTER_COLOR_EFFECT6,
    STATIC_GPU_FILTER_COLOR_EFFECT7,
    STATIC_GPU_FILTER_COLOR_EFFECT8,
    STATIC_GPU_FILTER_COLOR_EFFECT9,
    STATIC_GPU_FILTER_COLOR_EFFECT10,
    STATIC_GPU_FILTER_COLOR_EFFECT11,
    STATIC_GPU_FILTER_COLOR_EFFECT12,
    STATIC_GPU_FILTER_COLOR_EFFECT13,
    STATIC_GPU_FILTER_COLOR_EFFECT_LAST,
}eStaticColorFilter;
#endif

typedef enum
{
    STATIC_FILTER_TEXTURE_PAPER,
    STATIC_FILTER_TEXTURE_JEANS,
    STATIC_FILTER_TEXTURE_PAPER2,
    STATIC_FILTER_TEXTURE_COFFEE,
    STATIC_FILTER_TEXTURE_EARTH,
    STATIC_FILTER_TEXTURE_PAINTPEEL,
    STATIC_FILTER_TEXTURE_CONCRETE,
    STATIC_FILTER_TEXTURE_WALL,
    STATIC_FILTER_TEXTURE_STEEL,
    STATIC_FILTER_TEXTURE_OLDPAPER,
    STATIC_FILTER_TEXTURE_CARDBOARD,
    STATIC_FILTER_TEXTURE_PENCIL,
    STATIC_FILTER_TEXTURE_STROKES,
    STATIC_FILTER_TEXTURE_LAST
}eStaticTextureFilter;


typedef enum
{
    STATIC_FILTER_GRUNGE1,
    STATIC_FILTER_GRUNGE2,
    STATIC_FILTER_GRUNGE3,
    STATIC_FILTER_GRUNGE4,
    STATIC_FILTER_GRUNGE5,
    STATIC_FILTER_GRUNGE6,
    STATIC_FILTER_GRUNGE7,
    STATIC_FILTER_GRUNGE8,
    STATIC_FILTER_GRUNGE9,
    STATIC_FILTER_GRUNGE10,
    STATIC_FILTER_GRUNGE11,
    STATIC_FILTER_GRUNGE12,
    STATIC_FILTER_GRUNGE13,
    STATIC_FILTER_GRUNGE14,
    STATIC_FILTER_GRUNGE15,
    STATIC_FILTER_GRUNGE16,
    STATIC_FILTER_GRUNGE17,
    STATIC_FILTER_GRUNGE18,
    STATIC_FILTER_GRUNGE19,
    STATIC_FILTER_GRUNGE20,
    STATIC_FILTER_GRUNGE21,
    STATIC_FILTER_GRUNGE22,
    STATIC_FILTER_GRUNGE_LAST
}eStaticGrungeFilter;

#if SPACEGROUP_SUPPORT
typedef enum
{
    STATIC_FILTER_SPACE_ASTEROID,
    STATIC_FILTER_SPACE_DARKRED,
    STATIC_FILTER_SPACE_DEEPSKY,
    STATIC_FILTER_SPACE_RAYS,
    STATIC_FILTER_SPACE_LIGHTS,
    STATIC_FILTER_SPACE_SPARKLES,
    STATIC_FILTER_SPACE_GOLDENRED,
    STATIC_FILTER_SPACE_MIXEDCOLOR,
    STATIC_FILTER_SPACE_NEBULASTORM,
    STATIC_FILTER_SPACE_ORANGESPACE,
    STATIC_FILTER_SPACE_DUST,
    STATIC_FILTER_SPACE_GRUNGE1,
    STATIC_FILTER_SPACE_GRUNGE2,
    
    STATIC_FILTER_SPACE_LAST
}eStaticSpaceFilter;
#endif
#if BOKEHGROUP_SUPPORT
typedef enum
{
    STATIC_FILTER_BOKEH1,
    STATIC_FILTER_BOKEH2,
    STATIC_FILTER_BOKEH3,
    STATIC_FILTER_BOKEH4,
    STATIC_FILTER_BOKEH5,
    STATIC_FILTER_BOKEH6,
    STATIC_FILTER_BOKEH7,
    STATIC_FILTER_BOKEH8,
    STATIC_FILTER_BOKEH9,
    STATIC_FILTER_BOKEH10,
    STATIC_FILTER_BOKEH11,
    STATIC_FILTER_BOKEH12,
    STATIC_FILTER_BOKEH13,
    STATIC_FILTER_BOKEH14,
    STATIC_FILTER_BOKEH15,
    STATIC_FILTER_BOKEH16,
    STATIC_FILTER_BOKEH17,
    STATIC_FILTER_BOKEH18,
    STATIC_FILTER_BOKEH19,
    STATIC_FILTER_BOKEH20,
    STATIC_FILTER_BOKEH21,
    STATIC_FILTER_BOKEH22,
    STATIC_FILTER_BOKEH23,
    STATIC_FILTER_BOKEH24,
    STATIC_FILTER_BOKEH25,
    STATIC_FILTER_BOKEH26,
    STATIC_FILTER_BOKEH27,
    STATIC_FILTER_BOKEH28,
    STATIC_FILTER_BOKEH29,
    STATIC_FILTER_BOKEH30,
    STATIC_FILTER_BOKEH_LAST
}eStaticBokehFilter;
#endif
typedef  enum
{
    STATIC_FILTER_FRAME1,
    STATIC_FILTER_FRAME2,
    STATIC_FILTER_FRAME3,
    STATIC_FILTER_FRAME4,
    STATIC_FILTER_FRAME5,
    STATIC_FILTER_FRAME6,
    STATIC_FILTER_FRAME7,
    STATIC_FILTER_FRAME8,
    STATIC_FILTER_FRAME9,
    STATIC_FILTER_FRAME10,
    STATIC_FILTER_FRAME11,
    STATIC_FILTER_FRAME12,
    STATIC_FILTER_FRAME13,
    STATIC_FILTER_FRAME14,
    STATIC_FILTER_FRAME15,
    STATIC_FILTER_FRAME16,
    STATIC_FILTER_FRAME17,
    STATIC_FILTER_FRAME18,
    STATIC_FILTER_FRAME19,
    STATIC_FILTER_FRAME20,
    STATIC_FILTER_FRAME21,
    STATIC_FILTER_FRAME22,
    STATIC_FILTER_FRAME23,
    STATIC_FILTER_FRAME24,
    STATIC_FILTER_FRAME25,
    STATIC_FILTER_FRAME26,
    STATIC_FILTER_FRAME_LAST
}eStaticFrames;

typedef enum
{
    STATIC_FILTER_NOISE_LAST
}eStaticNoiseFilter;

@interface StaticFilterMapping : NSObject

+(NSString*)nameOfTheGroup:(int)grpId;
+(NSString*)nameOfFilterInGroup:(int)grpId atIndex:(int)index;
+(int)filterCountInGroup:(int)grpId;
+(int)staticFilterGroupCount;
+(int)getLockStatusOfFilter:(int)fil group:(int)grp;
+(void)setLockStatusOfFilter:(int)fil group:(int)grp to:(BOOL)newstatus;
+(BOOL)isFilterLockedOfGroup:(int)grpId atIndex:(int)index;
+(NSString*)productIdForGroup:(int)grpId;
@end
